### ISSUE TITLE
Extend the library to be able to add data to nodes

### ISSUE THREAD

**Issue by nponiros** [jriecken/dependency-graph#12]
Hi there,

I have a feature request. I was wondering if the library could be extended to enable the user to add a node with data

From what I can tell this would require 3 changes:

* the addNode method needs a 2nd parameter for the data (first parameter would be the node name and second parameter the data)
* a new method getData will be needed to get the data of a node by node name
* the hasNode method would need changes to be able to cope with falsy data (0, '', false, undefined, null)

Backwards compatibility should not be an issue if we keep the existing behavior when the addNode method gets undefined data. Only issue with this would be that a user will not be able to set undefined as data for a node.

In case you are interested in this functionality, I would gladly prepare a pull request.

Cheers
Nikolas

**Comment by jriecken** [comment]
Good idea, a pull request would be great!
