### ISSUE TITLE
Browser version?

### ISSUE THREAD

**Issue by armensg** [jriecken/dependency-graph#17]
Is there a version of this I can use for webapps in the browser?

**Comment by jriecken** [comment]
Not directly, but there are many bundlers out there that allow you to use JS modules in the browser - Browserify, Webpack, etc. I would suggest using one of those.

**Comment by armensg** [comment]
I tried to use browserfy before posting the question but it wouldn't work until I renamed "exports" to "window" in the source

On 7 Feb 2017, at 17:01, Jim Riecken <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #17<https://github.com/jriecken/dependency-graph/issues/17>.
