### ISSUE TITLE
Custom Error Types

### ISSUE THREAD

**Issue by MarkHerhold** [jriecken/dependency-graph#23]
Hi,

Thanks for the awesome library!

I'd like to be able to check the type of errors being thrown from dependency-graph. For example, `error instanceof DependencyCycleError` (or something similar).

Would you accept a PR for custom error types? If so, what Node.js versions should I target, or can I assume ES6+?

**Comment by jriecken** [comment]
Definitely! Can you target ES5 (This lib has been around for a long time and I don't want to inadvertently break anything for anyone using very old versions of node)
