### ISSUE TITLE
Types are wrong, causing a breaking change in 0.7.1

### ISSUE THREAD

**Issue by rhys-vdw** [jriecken/dependency-graph#26]
Types for `DepGraph` constructor are incorrect.

[Here](https://github.com/jriecken/dependency-graph/blame/c3ce05c176c97f7b06e7744c973bf75d0d8e20f2/lib/index.d.ts#L10) the `opts` argument is required.

[Here](https://github.com/jriecken/dependency-graph/blob/c3ce05c176c97f7b06e7744c973bf75d0d8e20f2/lib/dep_graph.js#L46) it is optional.

**Comment by jriecken** [comment]
Oops - fixed it (and released version 0.7.2)!

**Comment by rhys-vdw** [comment]
Cheers. :)
