### ISSUE TITLE
`addNode` should check if node already exists and throw error

### ISSUE THREAD

**Issue by vjpr** [jriecken/dependency-graph#3]
I just spent a heap of time tracking down a bug related to this.

If you add a node that already exists, all its edges will be reset to empty arrays which will probably always break something.

**Comment by jriecken** [comment]
Good catch - will definitely fix this!

**Comment by jriecken** [comment]
Released version 0.3.0

**Comment by jriecken** [comment]
Decided to just do nothing if a node already exists with the specified name, rather than throwing an error.
