### ISSUE TITLE
Restore a persisted Graph

### ISSUE THREAD

**Issue by pablitovicente** [jriecken/dependency-graph#44]
I have the requirement to save the graph and later restoring it from storage.

I'm saving the properties:

- nodes
- outgoingEdges
- incomingEdges
- circular

from the Graph instance and when I restore from storage I just create a Dependency-Graph instance and set those properties back.

A quick browse through the code seems to indicate this is safe to do this. Can someone confirm if they did this in the past and it's safe? should some extra state from the instance be saved?

**Comment by jriecken** [comment]
That is currently the only state in the graph so this should work. In the unlikely event that I change the format of the internal state (I have no plans to) it could break the restore though.

**Comment by pablitovicente** [comment]
@jriecken thanks for your answer, after a few weeks using that method all seems right; good point about changes to the internal state format.

Will it make sense for me to attempt to send PR that simply returns the internal state that is important to restore a graph so user can then persist it somewhere?
