### ISSUE TITLE
order function which takes a name and returns [dependenciesOf(name)..., name, dependsOf(name)...]

### ISSUE THREAD

**Issue by vjpr** [jriecken/dependency-graph#5]
Similar to `overallOrder`, but just for a single dependency.

Use case: When used as an event trigger to run before and after hooks (which have interdependencies).

**Comment by jriecken** [comment]
Seems like the output in this case would be in a strange order - It would contain:

- closest dependencies of `name`
- further away dependencies of `name`
- `name`
- closest dependants of `name`
- further away dependencies of `name`

which seems backwards for the dependencies part of the result.

Can you give a concrete example?

**Comment by vjpr** [comment]
Sorry. I was mixing up dependencies and events in my head.

I want to do something like `app.trigger('task')` which would run its dependencies, and then trigger its dependants to run. Every task could run `before`, `after` or `between` other tasks.

The between tasks became difficult. I think what I actually need is to separate tasks and events. Tasks having dependencies. Events having before and after callbacks.
